### ISSUE TITLE
advice

### ISSUE THREAD

**Issue by BnanZ0** [T1ckbase/cs2-rainbow-crosshair#3]
could add t1ckbase_rainbow_crosshair_5.cfg
content:cl_crosshaircolor "5"; bind "mouse_x" "T1ckbaseRainbow; yaw"; bind "mouse_y" "T1ckbaseRainbow; pitch"
add alias "rainbow_crosshair_enable" "exec t1ckbase_rainbow_crosshair_5" to t1ckbase_rainbow_crosshair.cfg
this could make it easier to toggle in-game, also if someone using "cl_crosshaircolor" then cl_crosshaircolor "5" is required otherwise the RGB effect won't show up

**Comment by T1ckbase** [comment]
Ok, I will add it

**Comment by T1ckbase** [comment]
Do you have this problem?
![Screenshot 2023-10-14 17-19-50](https://github.com/T1ckbase/cs2-rainbow-crosshair/assets/146760065/e1f1249e-8a0e-4f07-828e-224d7ed59826)

**Comment by BnanZ0** [comment]
Not seeing this problem on the first version u made, I just simply add those things that I mentioned above, I will try ur new version and see how it works later

**Comment by BnanZ0** [comment]
It shows this but rgb works normally
![image](https://github.com/T1ckbase/cs2-rainbow-crosshair/assets/110257560/382b8618-b6d2-435e-8ff1-56c2f900dde1)

**Comment by BnanZ0** [comment]
Just add cl_crosshaircolor "5" in t1ckbase_rainbow_crosshair_enable.cfg  then it works fine for me

**Comment by T1ckbase** [comment]
Ok

**Comment by BnanZ0** [comment]
Also, I managed to add new features like "toggle" etc from the newest version into the first version, but those command buffer full issues didn't occur.
It's kinda weird
Here is the file, u can try and see how it works
[rgb.zip](https://github.com/T1ckbase/cs2-rainbow-crosshair/files/12906242/rgb.zip)
