### ISSUE TITLE
won't work

### ISSUE THREAD

**Issue by cs2-93** [T1ckbase/cs2-rainbow-crosshair#4]
when exec t1ckbase_rainbow_crosshair -> it says couldnt exec because it cannot read the actual  t1ckbase_rainbow_crosshair.cfg

when t1ckbase_rainbow_crosshair_enable -> unknown comand

when moving mouse around -> says in console "Unknown command: T1ckbaseRainbow"

Maybe no longer works because the after cs2 updates?

**Comment by T1ckbase** [comment]
I just tested it and it works, maybe you put cfg in the wrong location?

**Comment by cs2-93** [comment]
can you provide me with the correct location in which autoexec.cfg should be, because bow it's in main, folder, cfg folder and outside of cfg folder and still won't load the script

**Comment by T1ckbase** [comment]
Steam\steamapps\common\Counter-Strike Global Offensive\game\csgo\cfg

**Comment by cs2-93** [comment]
i will take a second look, but i know is put there alongside with all the cfgs provided, name of the autoexec is "autoexec" (and format is .cfg) with the line that you provided inside writen with notepad, is there anything else to be added to the line so the line to take effect or exactly how it's given, and there other launch comands that i may write to the launcher of the game?

**Comment by cs2-93** [comment]
case solved,  was confusion between Steam\steamapps\common\Counter-Strike Global Offensive\game\csgo\cfg and Steam\steamapps\common\Counter-Strike Global Offensive\csgo\cfg
