### ISSUE TITLE
can you get it to work without mouse movement?

### ISSUE THREAD

**Issue by mr-pepe69** [T1ckbase/cs2-rainbow-crosshair#5]
i would love to see it change at a static phase. so it loop trough the colours at 1, 2, 3 or whatever seconds you add. it would make it way cooler. anyway, great CFG budd.

**Comment by T1ckbase** [comment]
It's not possible to change colors based on time using just cfg, this is the closest I can get.

**Comment by T1ckbase** [comment]
This is possible if Valve fixes this issue.
[https://github.com/ValveSoftware/csgo-osx-linux/issues/3603](https://github.com/ValveSoftware/csgo-osx-linux/issues/3603)
